# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WUSTLNutrition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ChameleonFramework/Swift'
  
  #pod 'Charts', '~> 3.0.1'
  #pod 'SwiftCharts', '~> 0.6'
  pod 'Charts'

  # Pods for WUSTLNutrition

  target 'WUSTLNutritionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WUSTLNutritionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
